// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectToChatroom() {
  return window['go']['main']['App']['ConnectToChatroom']();
}

export function DisconnectFromChatroom() {
  return window['go']['main']['App']['DisconnectFromChatroom']();
}

export function GetMessages() {
  return window['go']['main']['App']['GetMessages']();
}

export function IsConnected() {
  return window['go']['main']['App']['IsConnected']();
}

export function ListenForMessage() {
  return window['go']['main']['App']['ListenForMessage']();
}

export function SendMsgToChatRoom(arg1) {
  return window['go']['main']['App']['SendMsgToChatRoom'](arg1);
}
