// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {global} from '../models';

export function ConnectToChatroom():Promise<void>;

export function DisconnectFromChatroom():Promise<void>;

export function GetMessages():Promise<Array<global.Message>>;

export function IsConnected():Promise<boolean>;

export function ListenForMessage():Promise<void>;

export function SendMsgToChatRoom(arg1:string):Promise<void>;
